# Generated by Django 5.1.1 on 2024-09-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='objects_name',
            field=models.CharField(max_length=100, verbose_name='Name of object'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='rooms',
            field=models.IntegerField(verbose_name='Number of rooms'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('STUDIO', 'Studio')], default='APARTMENT', max_length=20, verbose_name='Type of object'),
        ),
    ]
