# Generated by Django 5.1.1 on 2024-09-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartment", "0002_housing_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housing",
            name="type",
            field=models.CharField(
                choices=[
                    ("APARTMENT", "Apartment"),
                    ("HOUSE", "House"),
                    ("STUDIO", "Studio"),
                    ("CASTLE", "Castle"),
                ],
                default="APARTMENT",
                max_length=20,
                verbose_name="Type of object",
            ),
        ),
    ]
