# Generated by Django 5.1.1 on 2024-09-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_alter_housing_objects_name_alter_housing_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=6, verbose_name='Haus number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=100, verbose_name='Index'),
        ),
    ]
