# Generated by Django 5.1.1 on 2024-09-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartment", "0004_alter_housing_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="housing",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
