# Generated by Django 5.1.1 on 2024-09-08 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartment", "0005_housing_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="housing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="housing",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="housing",
                to="apartment.address",
            ),
        ),
    ]
