# Generated by Django 5.1 on 2024-09-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_housing_created_at_alter_housing_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housing',
            options={'verbose_name': 'Housing', 'verbose_name_plural': 'Housings'},
        ),
    ]
