# Generated by Django 5.1 on 2024-09-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_housing_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('STUDIO', 'Studio'), ('CASTLE', 'Castle'), ('HOTEL', 'Hotel')], default='APARTMENT', max_length=20, verbose_name='Type of object'),
        ),
    ]
