# Generated by Django 5.1.1 on 2024-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_remove_housing_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Haus number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street'),
        ),
    ]
