# Generated by Django 5.1.1 on 2024-09-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housing',
            old_name='name',
            new_name='objects_name',
        ),
    ]
