# Generated by Django 5.1.1 on 2024-09-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_name_housing_objects_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('STUDIO', 'Studio')], default='A', max_length=20, verbose_name='Type'),
        ),
    ]
