# Generated by Django 5.1.1 on 2024-09-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_housing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Housing',
        ),
    ]
